export const WORD_LIST = [
    { word: "CELLS", fact: "All living organisms are made of cells, the basic building blocks of life." },
    { word: "PLANT", fact: "Plants are the primary producers of oxygen on Earth through photosynthesis." },
    { word: "BRAIN", fact: "The human brain contains about 86 billion neurons communicating via electrical signals." },
    { word: "HEART", fact: "The human heart is a muscle that pumps about 2,000 gallons of blood every day." },
    { word: "BLOOD", fact: "Blood is a liquid tissue that transports oxygen, nutrients, and waste throughout the body." },
    { word: "LIVER", fact: "The liver is the only organ in the human body that can regenerate itself completely." },
    { word: "LUNGS", fact: "The surface area of both human lungs is roughly the size of a tennis court." },
    { word: "SNAKE", fact: "Snakes are cold-blooded reptiles that smell using their tongues and the roof of their mouths." },
    { word: "SMILE", fact: "Smiling releases endorphins and dopamine, which act as natural stress relievers." },
    { word: "WATER", fact: "Most biological processes occur in water, which makes up about 60% of our body weight." },
    { word: "GREEN", fact: "Chlorophyll is the pigment that gives plants their green color and absorbs sunlight." },
    { word: "NERVE", fact: "Nerve impulses can travel through the human body at speeds of up to 270 miles per hour." },
    { word: "SKULL", fact: "The human skull is actually made of 22 different bones fused together." },
    { word: "ORGAN", fact: "An organ is a collection of tissues that structurally form a functional unit." },
    { word: "FRUIT", fact: "A botanical fruit is the seed-bearing structure in flowering plants." },
    { word: "ALGAE", fact: "Algae produce over half of the world's oxygen supply through photosynthesis." },
    { word: "VIRUS", fact: "Viruses are microscopic parasites that can only reproduce inside a host's living cells." },
    { word: "BONES", fact: "Adult humans have 206 bones, while babies are born with about 270." },
    { word: "SIGHT", fact: "The human eye can distinguish approximately 10 million different colors." },
    { word: "SLEEP", fact: "Sleep is essential for the brain to flush out toxins and consolidate memories." },
    { word: "SNAIL", fact: "Some snails can sleep for up to three years if the weather is too dry." },
    { word: "TIGER", fact: "Tiger skin is also striped, not just their fur; no two tigers have the same pattern." },
    { word: "FEVER", fact: "A fever is the body's way of fighting infections by making it too hot for germs to survive." },
    { word: "TEETH", fact: "Tooth enamel is the hardest substance in the human body." },
    { word: "FLOWER", fact: "Flowers are the reproductive organs of plants, designed to attract pollinators." },
    { word: "GENES", fact: "Genes are segments of DNA that act as instructions to build molecules called proteins." },
    { word: "SWEAT", fact: "Sweat is odorless; the smell is actually caused by bacteria breaking it down on your skin." },
    { word: "WHALE", fact: "The blue whale's heart is so large that a human could swim through its arteries." },
    { word: "MOUTH", fact: "The human mouth is home to over 700 different species of bacteria." },
    { word: "SKINS", fact: "Skin is the largest organ of the body and protects us from microbes and the elements." },
    { word: "ADAPT", fact: "Adaptation is the process by which a species becomes better suited to its environment." },
    { word: "LARVA", fact: "A larva is a distinct juvenile form many animals undergo before metamorphosis." },
    { word: "FUNGI", fact: "Fungi are more closely related to animals than they are to plants." },
    { word: "SEEDS", fact: "The oldest seed ever grown was 32,000 years old before it successfully sprouted!" },
    { word: "TASTE", fact: "Your tongue has about 10,000 taste buds, which are replaced every two weeks." },
    { word: "WINGS", fact: "Bird wings are actually modified front limbs with bones similar to human arms." },
    { word: "BELLY", fact: "Your belly button is home to a unique ecosystem of thousands of types of bacteria." },
    { word: "FROGS", fact: "Frogs don't drink water; they absorb it through their skin." },
    { word: "GRASS", fact: "Bamboo is the fastest-growing grass; some species grow 35 inches in a single day." },
    { word: "STING", fact: "Honeybees die after stinging because their stinger is barbed and pulls out their organs." },
    { word: "TOUCH", fact: "Your fingertips are so sensitive they can detect a ridge only 13 nanometers high." },
    { word: "YEAST", fact: "Yeast is a single-celled fungus used in baking to make bread rise." },
    { word: "PEALS", fact: "Oysters create pearls as a defense mechanism against irritants like sand." },
    { word: "LIGHT", fact: "Bioluminescence is light produced by a chemical reaction within a living organism." },
    { word: "CHIMP", fact: "Humans and chimpanzees share about 98.8% of the same DNA." },
    { word: "SPINE", fact: "The human spine consists of 33 individual vertebrae that protect the spinal cord." },
    { word: "SPORE", fact: "Spores are single-celled reproductive units that can survive harsh environments." },
    { word: "URINE", fact: "The kidneys filter about 150 quarts of blood daily to produce urine." },
    { word: "MAMMA", fact: "Mammals are defined by having hair or fur and producing milk for their young." },
    { word: "OVARY", fact: "In plants, the ovary is the part of the pistil that holds the ovules." }
];