export const WORD_LIST = [
    "APPLE", "BEACH", "BRAIN", "BREAD", "BRUSH", "CHAIR", "CHEST", "CHORD",
    "CLICK", "CLOCK", "CLOUD", "DANCE", "DIARY", "DRINK", "DRIVE", "EARTH",
    "FEAST", "FIELD", "FRUIT", "GLASS", "GRAPE", "GREEN", "GHOST", "HEART",
    "HOUSE", "JUICE", "LIGHT", "LEMON", "MELON", "MONEY", "MUSIC", "NIGHT",
    "OCEAN", "PARTY", "PIANO", "PILOT", "PLANE", "PHONE", "PIZZA", "PLANT",
    "RADIO", "RIVER", "ROBOT", "SHIRT", "SHOES", "SMILE", "SNAKE", "SPACE",
    "SPOON", "STORM", "TABLE", "TIGER", "TOAST", "TOUCH", "TRAIN", "TRUCK",
    "VOICE", "WATER", "WATCH", "WHALE", "WORLD", "WRITE", "YOUTH", "ZEBRA",
    "ADULT", "AGENT", "ANGER", "APPLE", "AWARD", "BASIS", "BOARD", "CHESS",
    "COACH", "COURT", "DRAMA", "DREAM", "EVENT", "FAITH", "FOCUS", "FRAME",
    "GUIDE", "HOTEL", "IMAGE", "INPUT", "JUDGE", "KNIFE", "LAYER", "LEVEL",
    "LIMIT", "LUNCH", "MAJOR", "MATCH", "METAL", "MODEL", "MOTOR", "MOUTH",
    "NOISE", "NORTH", "NOVEL", "NURSE", "OFFER", "ORDER", "PAPER", "PATCH"
];